server:
  port: 8080
  #  ssl:
  #    key-store:
  #    key-store-password: secret
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json, application/xml, application/pdf
  tomcat:
    accesslog:
      enabled: true
      pattern: "%t %a \"%r\" %s (%D ms)"
    basedir: /home/vickykatoch/run/spa-web-server/logs
spring:
  web:
    resources:
      static-locations: file:/home/vickykatoch/run/spa-web-server/assets, file:/home/vickykatoch/run/spa-web-server/appConfigs
  application:
    name: SPAWebServer
logging:
  level:
    ROOT: DEBUG

spa:
  app-config-loc: /home/vickykatoch/run/spa-web-server/appConfigs/
  app-name: react-web-app
  assets-loc: /home/vickykatoch/run/spa-web-server/assets/
  config-route-name: appConfigs
  supportedMimeTypes: "html,js,json,css,csv,gif,jpeg,jpg,png,ico,svg,tff,woff,woff2,yaml,map,appcache,pdf,zip"
  cacheDuration: 3600 # seconds, 0 means no-caching
  etag:
    enabled: true
